version: '3.10'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:5000/api
    depends_on:
      - backend
  backend:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app  
      - ./instance:/app/instance
    working_dir: /app
    environment:
      - LOCAL_RESTFUL_EVENT_URL=http://backend:5000/api/event/events
      - FLASK_APP=app.py
    command: python app.py